export const fallbackOpportunities = [
  {
    slug: 'cafe-riyadh',
    title: 'مقهى قائم في شمال الرياض',
    sector: 'مطاعم ومقاهي',
    city: 'الرياض',
    type: 'بيع كامل',
    value: '450,000 ريال',
    revenue: '780,000 ريال',
    profit: '180,000 ريال',
    verification: 'مراجعة مبدئية',
    risk: 'متوسط',
    readiness: 'جاهز للتواصل',
    summary: 'فرصة تشغيلية قائمة في موقع نشط.',
    description: 'مقهى قائم يحتاج إلى مراجعة الإيرادات، عقد الإيجار، التراخيص، وقائمة الأصول.',
    strengths: ['موقع قائم', 'تشغيل يومي واضح', 'قابلية تحسين المبيعات'],
    risks: ['فحص الإيرادات', 'مراجعة عقد الإيجار', 'تحليل التكاليف'],
    documents: ['السجل التجاري', 'الرخص', 'عقد الإيجار', 'قائمة الأصول']
  },
  {
    slug: 'perfume-store',
    title: 'متجر إلكتروني متخصص في العطور',
    sector: 'تجارة إلكترونية',
    city: 'الرياض',
    type: 'تنازل',
    value: '220,000 ريال',
    revenue: '420,000 ريال',
    profit: '95,000 ريال',
    verification: 'بيانات أساسية',
    risk: 'متوسط',
    readiness: 'يحتاج فحص',
    summary: 'متجر قائم مع قاعدة عملاء أولية.',
    description: 'متجر إلكتروني يحتاج إلى مراجعة المبيعات، التوريد، التسويق، وهوامش الربح.',
    strengths: ['نشاط قائم', 'قابلية تطوير التسويق', 'منتج قابل للتوسع'],
    risks: ['تكلفة الإعلانات', 'اعتماد على الموردين', 'فحص الطلبات الفعلية'],
    documents: ['بيانات المبيعات', 'حسابات المنصات', 'عقود الموردين']
  },
  {
    slug: 'plastic-factory',
    title: 'مصنع صغير للمنتجات البلاستيكية',
    sector: 'صناعة',
    city: 'الدمام',
    type: 'شراكة',
    value: '1,200,000 ريال',
    revenue: '2,400,000 ريال',
    profit: '420,000 ريال',
    verification: 'جاهز للفحص',
    risk: 'متوسط',
    readiness: 'ملف مكتمل',
    summary: 'منشأة صناعية صغيرة تحتاج إلى فحص تشغيلي.',
    description: 'فرصة صناعية تتطلب مراجعة الطاقة الإنتاجية، الأصول، العقود، الموردين، والتراخيص.',
    strengths: ['أصول قائمة', 'طلب تشغيلي محتمل', 'قابلية التوسع'],
    risks: ['تكلفة المواد الخام', 'حالة المعدات', 'الالتزامات التشغيلية'],
    documents: ['قائمة الأصول', 'الرخص الصناعية', 'عقود الموردين', 'بيانات مالية']
  },
  {
    slug: 'saas-booking',
    title: 'منصة SaaS لإدارة الحجوزات',
    sector: 'تقنية',
    city: 'جدة',
    type: 'استثمار',
    value: '300,000 ريال',
    revenue: '120,000 ريال',
    profit: 'غير مستقر',
    verification: 'مرحلة مبكرة',
    risk: 'مرتفع',
    readiness: 'قيد التطوير',
    summary: 'مشروع تقني في مرحلة نمو مبكرة.',
    description: 'منصة تقنية تحتاج إلى مراجعة المنتج، المستخدمين، الاشتراكات، وخطة النمو.',
    strengths: ['قابلية التوسع', 'نموذج اشتراكات', 'سوق قابل للنمو'],
    risks: ['مرحلة مبكرة', 'حاجة لتطوير مستمر', 'مخاطر اكتساب العملاء'],
    documents: ['بيانات المستخدمين', 'خارطة المنتج', 'تحليل السوق']
  }
];

export function normalizeOpportunity(row) {
  return {
    slug: row.slug || row.id,
    title: row.title || 'فرصة بدون عنوان',
    sector: row.sector || 'غير محدد',
    city: row.city || 'غير محدد',
    type: row.opportunity_type || row.type || 'غير محدد',
    value: row.asking_value || row.value || 'غير معلن',
    revenue: row.revenue_estimate || row.revenue || 'غير معلن',
    profit: row.profit_estimate || row.profit || 'غير معلن',
    verification: row.verification_status || row.verification || 'بيانات أساسية',
    risk: row.risk_level || row.risk || 'متوسط',
    readiness: row.readiness_status || row.readiness || 'يحتاج فحص',
    summary: row.summary || 'فرصة تجارية تحتاج إلى فحص مستقل.',
    description: row.description || row.summary || 'فرصة تجارية تحتاج إلى مراجعة مستقلة.',
    strengths: row.strengths || ['بيانات أولية متاحة', 'قابلة للمراجعة'],
    risks: row.risks || ['فحص الأرقام', 'مراجعة الالتزامات'],
    documents: row.documents || ['السجل أو الرخص', 'بيانات مالية'],
    provided_via: row.provided_via || row.submitter_type || null
  };
}
